# Generated by Django 4.2.2 on 2023-07-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={
                "ordering": ["organization", "date", "item"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AddField(
            model_name="payments",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="directory.currencies",
            ),
        ),
    ]
