# Generated by Django 4.2.2 on 2023-11-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentdocuments", old_name="by_request", new_name="by_plan",
        ),
    ]
