# Generated by Django 4.2.2 on 2023-10-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_alter_initialdebts_type_debt"),
        ("payments", "0002_paymentsplan_name_series"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_calc",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("constant", "Constant payments"),
                            ("annuity", "Credit: annuity"),
                            ("differential", "Credit: differentiated"),
                        ],
                        max_length=200,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, unique=True)),
                ("is_cash", models.BooleanField(default=False)),
                ("comments", models.CharField(max_length=250)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15),
                ),
                ("date_first", models.DateField(blank=True)),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.counterparties",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.currencies",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.expensesitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.project",
                    ),
                ),
            ],
        ),
    ]
