# Generated by Django 4.2.2 on 2023-11-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alter_paymentdocumentplan_inflow_amount_and_more"),
        ("payments", "0002_rename_by_request_paymentdocuments_by_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdocuments",
            name="by_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="planning.paymentdocumentplan",
            ),
        ),
    ]
