# Generated by Django 4.2.2 on 2023-10-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_calculations"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculations",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("annually", "annually"),
                    ("monthly", "monthly"),
                    ("weekly", "weekly"),
                    ("daily", "daily"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calculations",
            name="loan_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
