# Generated by Django 4.2.2 on 2023-11-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_alter_items_group"),
        ("payments", "0003_alter_paymentdocuments_by_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="changepayaccount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="directory.organization",
            ),
        ),
        migrations.AlterField(
            model_name="changepayaccount",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="directory.currencies",
            ),
        ),
    ]
