# Generated by Django 4.2.2 on 2023-10-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_remove_paymentsplan_name_series_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculations",
            name="term",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
