# Generated by Django 4.2.2 on 2023-11-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_remove_paymentaccount_open_balance_and_more"),
        ("payments", "0006_calculations_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculations",
            name="comments",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("annually", "annually"),
                    ("monthly", "monthly"),
                    ("weekly", "weekly"),
                    ("daily", "daily"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="is_cash",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="directory.project",
            ),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="type_calc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("constant", "Constant payments"),
                    ("annuity", "Credit: annuity"),
                    ("differential", "Credit: differentiated"),
                ],
                max_length=200,
            ),
        ),
    ]
