# Generated by Django 4.2.2 on 2023-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_calculations_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculations",
            name="flow",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("receipt", "R+"), ("payment", "P-")],
                default="payment",
                max_length=10,
            ),
        ),
    ]
