# Generated by Django 4.2.2 on 2023-11-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_calc",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("constant", "Constant payments"),
                            ("annuity", "Credit: annuity"),
                            ("differential", "Credit: differentiated"),
                        ],
                        default="constant",
                        max_length=200,
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        blank=True,
                        choices=[("payments", "Receipts"), ("payments", "Payments")],
                        default="payments",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, unique=True)),
                ("is_cash", models.BooleanField(blank=True, default=False)),
                ("comments", models.CharField(blank=True, max_length=250, null=True)),
                ("date_first", models.DateField(blank=True)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=15),
                ),
                ("term", models.IntegerField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("annually", "annually"),
                            ("monthly", "monthly"),
                            ("weekly", "weekly"),
                            ("daily", "daily"),
                        ],
                        default="monthly",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "loan_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.counterparties",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.currencies",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.expensesitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptsPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_cash", models.BooleanField(default=False)),
                ("comments", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.counterparties",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.currencies",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.incomeitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt plan",
                "verbose_name_plural": "Receipts plan",
                "ordering": ["organization", "date", "item"],
            },
        ),
        migrations.CreateModel(
            name="PaymentsPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_cash", models.BooleanField(default=False)),
                ("comments", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planning.calculations",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.counterparties",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.currencies",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.expensesitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="directory.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment plan",
                "verbose_name_plural": "Payments plan",
                "ordering": ["date", "item"],
            },
        ),
    ]
