# Generated by Django 4.2.2 on 2023-11-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdocumentplan",
            name="inflow_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="paymentdocumentplan",
            name="outflow_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
