# Generated by Django 4.2.2 on 2023-11-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alter_paymentdocumentplan_inflow_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdocumentplan",
            name="calculation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="planning.calculations",
            ),
        ),
    ]
