# Generated by Django 4.2.2 on 2023-11-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_alter_calculations_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculations",
            name="flow",
            field=models.CharField(
                blank=True,
                choices=[("receipts", "Receipts"), ("payments", "Payments")],
                default="payments",
                max_length=10,
            ),
        ),
    ]
