# Generated by Django 4.2.2 on 2023-09-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_alter_paymentaccount_open_balance_and_more"),
        ("registers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsettings",
            name="accounting_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="directory.currencies",
            ),
        ),
    ]
