name: Docker

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: alata9/enterprise_finance


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}" -t "${{ env.REGISTRY }}/${{ github.repository }}:latest" .
          docker push --all-tags "${{ env.REGISTRY }}/${{ github.repository }}"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Deployment
        # You may pin to the exact commit or the version.
        uses: wshihadeh/docker-deployment-action@v2
        with:
          # Remote Docker host ie (user@host)
          remote_docker_host: root@46.101.6.70
          # Remote Docker ssh port ie (22)
          remote_docker_port: 22
          # Remote Docker SSH public key
          ssh_public_key: ${{ secrets.SSH_KNOWN }}
          # SSH private key used to connect to the docker host
          ssh_private_key: ${{ secrets.SSH_KEY }}
          # Deployment mode either docker-swarm or docker-compose. Default is docker-compose.
          deployment_mode: docker-compose
          deploy_path: /root/my-django-app
          stack_file_name: docker-compose.yml
          # A boolean input to trigger docker prune command.
          # docker_prune: true
          # The args for the pre deploument command.
          args: up -d
