# Generated by Django 4.2.2 on 2023-09-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentaccount",
            name="open_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="paymentaccount", name="open_date", field=models.DateField(),
        ),
    ]
