# Generated by Django 4.2.2 on 2023-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="activity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="items",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sales_income", "Sales income"),
                    ("Direct_expenses", "Direct expenses"),
                    ("Administrative_expenses", "Administrative expenses"),
                    ("Commercial_expenses", "Commercial expenses"),
                    ("Production_costs", "Production costs"),
                    ("Other", "Other income and expenses"),
                    ("Loans", "Credits and loans"),
                    ("Fixed_assets", "Fixed assets"),
                    ("New_projects", "New projects"),
                    ("Change_account", "Change payment account"),
                ],
                max_length=100,
            ),
        ),
    ]
