# Generated by Django 4.2.2 on 2023-11-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                (
                    "flow",
                    models.CharField(
                        blank=True,
                        choices=[("inflows", "inflows"), ("outflows", "outflows")],
                        default="outflow",
                        max_length=10,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("loans", "Credits and loans"),
                            ("assets", "Fixed assets"),
                            ("other_assets", "Other noncurrent assets"),
                            ("projects", "New projects"),
                            ("sales", "Sales income"),
                            ("admin_costs", "Administrative expenses"),
                            ("commerce_costs", "Commercial expenses"),
                            ("product_costs", "Production costs"),
                            ("direct_costs", "Direct expenses"),
                            ("other", "Other income and expenses"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["group", "item"],
            },
        ),
    ]
