# Generated by Django 4.2.2 on 2023-10-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialdebts",
            name="type_debt",
            field=models.CharField(
                choices=[
                    ("Lender", "Lender"),
                    ("Borrower", "Borrower"),
                    ("Other", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
