# Generated by Django 4.2.2 on 2023-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_alter_initialdebts_type_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialdebts",
            name="type_debt",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Lender", "Lender"),
                    ("Borrower", "Borrower"),
                    ("Other", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
