# Generated by Django 4.2.2 on 2023-09-02 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_alter_paymentaccount_open_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrenciesRates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="directory.currencies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate",
                "verbose_name_plural": "Exchange rates",
                "ordering": ["date", "currency"],
            },
        ),
    ]
