# Generated by Django 4.2.2 on 2023-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="flow",
            field=models.CharField(
                blank=True,
                choices=[("Receipts", "Receipts"), ("Payments", "Payments")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sales_income", "Sales income"),
                    ("Direct_expenses", "Direct expenses"),
                    ("Administrative_expenses", "Administrative expenses"),
                    ("Commercial_expenses", "Commercial expenses"),
                    ("Production_costs", "Production costs"),
                    ("Other", "Other income and expenses"),
                    ("Loans", "Credits and loans"),
                    ("Fixed_assets", "Fixed assets"),
                    ("Other_noncurrent_assets", "Other noncurrent assets"),
                    ("New_projects", "New projects"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="item",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
