# Generated by Django 4.2.2 on 2023-11-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_items_activity_alter_items_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="items",
            name="system_field",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="items",
            name="activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("operating", "operating"),
                    ("financing", "financing"),
                    ("investing", "investing"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
