# Generated by Django 4.2.2 on 2023-11-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_items_item_user_items_system_field_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="items",
            options={
                "ordering": ["group", "name"],
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.RemoveField(model_name="items", name="item",),
        migrations.RemoveField(model_name="items", name="system_field",),
        migrations.AddField(
            model_name="items",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="items",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sales_income", "Sales income"),
                    ("Direct_expenses", "Direct expenses"),
                    ("Administrative_expenses", "Administrative expenses"),
                    ("Commercial_expenses", "Commercial expenses"),
                    ("Production_costs", "Production costs"),
                    ("Other", "Other income and expenses"),
                    ("Loans", "Credits and loans"),
                    ("Fixed_assets", "Fixed assets"),
                    ("New_projects", "New projects"),
                ],
                max_length=100,
            ),
        ),
    ]
