# Generated by Django 4.2.2 on 2023-11-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_alter_initialdebts_type_debt"),
    ]

    operations = [
        migrations.RemoveField(model_name="paymentaccount", name="open_balance",),
        migrations.RemoveField(model_name="paymentaccount", name="open_date",),
    ]
