# Generated by Django 4.2.2 on 2023-09-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_currenciesrates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currenciesrates",
            options={
                "ordering": ["date", "accounting_currency", "currency"],
                "verbose_name": "Rate",
                "verbose_name_plural": "Currency rates",
            },
        ),
        migrations.AddField(
            model_name="currenciesrates",
            name="accounting_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cur1",
                to="directory.currencies",
            ),
        ),
        migrations.AlterField(
            model_name="currenciesrates",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cur2",
                to="directory.currencies",
            ),
        ),
    ]
