# Generated by Django 4.2.2 on 2023-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_alter_currenciesrates_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currenciesrates",
            name="rate",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
    ]
